name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  scan_ruby:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'  # Adjust as necessary
          bundler-cache: true

      - name: Install Bundler
        run: gem install bundler

      - name: Show Environment Variables
        run: printenv

      - name: Fix script permissions
        run: |
          chmod +x bin/brakeman
          chmod +x bin/importmap
          chmod +x bin/rubocop
          chmod +x bin/rails

      - name: Scan for common Rails security vulnerabilities using static analysis
        run: ruby bin/brakeman --no-pager

  # Other jobs remain the same...
